name: Workflow Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: nearform/optic-release-automation-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          semver: ${{ github.event.inputs.semver }}
          sync-semver-tags: true